version: '3'
services:
  web1:
    build:
      context: ./project1
      dockerfile: dockerfile
    ports:
      - "8001:8001"
  web2:
    build:
      context: ./project2
      dockerfile: dockerfile
    ports:
      - "8002:8002"
  web3:
    build:
      context: ./project3
      dockerfile: dockerfile
    ports:
      - "8003:8003"
  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - web1
      - web2
      - web3
